### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by androw** [Ultimaker/Scripta_public#2]
Would it be possible to add a LICENCE to the code?

**Comment by jellespijker** [comment]
Sure, since it is compiled with CuraEngine it will probably be AGPLv3.

Curious why you ask this, since the code in this project will for all intent and practices be optimized away when compiling CuraEngine.

Will discuss internally which license will be applicable

**Comment by androw** [comment]
I thought it was a new dep for building curaengine 5.4.0 which ask for scripta on build and so I was thinking of maybe packaging this.
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/46012/pipelines

**Comment by jellespijker** [comment]
It is a dependency and you need it to build CuraEngine.  But the code in itself has no functionality.  It is a placeholder for our VisualDebugger. Which is only used and distributed internally in the company. If we need to debug complex shapes and geometric problems we can overload this plugin such that we can analyze the algorithms. 
since this impacts the performance we only use that Visual Debugger internally and we don't ship it with the binaries. 

For all intent and purposes you can assume that the code in this repository has a AGPLV3 compatible license.

the calls will be optimized away when compiled with this library 
https://github.com/Ultimaker/Scripta_public/blob/main/include/scripta/logger.h#L14

**Comment by jellespijker** [comment]
Discussed it internally and we decided to release this public dependency under the same license as the engine, which is AGPLv3

https://github.com/Ultimaker/Scripta_public/blob/main/LICENSE
